---
- name: gather package facts
  package_facts:

- name: start and enable snapd.socket
  service:
    name: snapd.socket
    state: started
    enabled: yes
  when: "'snapd' in ansible_facts.packages"

- name: get stats of /var/lib/snapd/snap
  stat:
    path: /var/lib/snapd/snap
  register: var_lib_snapd_snap

- name: create symbolic link to /var/lib/snapd/snap
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link
  when: var_lib_snapd_snap.stat.exists

- name: snap install core
  snap:
    name: core
  when: "'snapd' in ansible_facts.packages"

- name: snap install certbot
  snap:
    name: certbot
    classic: true
  when: "'snapd' in ansible_facts.packages"

- name: get stats of /snap/bin/certbot
  stat:
    path: /snap/bin/certbot
  register: snap_bin_certbot

- name: create symbolic link to /snap/bin/certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    state: link
  when: snap_bin_certbot.stat.exists
